version: 2

jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:
      - checkout

      - run:
          name: Mac info
          command: system_profiler SPSoftwareDataType

      - run:
          name: Run Swift tests
          command: make test-swift
          environment:
            SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__

      - run:
          name: Run macOS tests
          command: make test-macos
          environment:
            SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__

      - run:
          name: Run playground tests
          command: make test-playgrounds
          environment:
            SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__

      - store_artifacts:
          path: /tmp/__SnapshotArtifacts__

      - save_cache:
          key: build-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".build"

      - save_cache:
          key: derivedData-cache-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".derivedData"
