version: 2

jobs:
  build:
    macos:
      xcode: "10.1.0"

    steps:
      - checkout

      - run:
          name: Mac info
          command: system_profiler SPSoftwareDataType

      - run:
          name: Run Swift tests
          command: make test-swift
          environment:
            SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__

      - store_artifacts:
          path: /tmp/__SnapshotArtifacts__
